# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21967a33ef3bc25801d36db27f6a1d5491bb823a562d6ab8685b4b63a04de9d524ab51fa6f3b28525aff51cacdf6e0613beb8cc958fb75cf5cfd1daacdac2685

test:
  secret_key_base: 8107e1d866ea6310682ea46aa689204c7a266a596d54ab46054c72392bdf27b1d15df441aadf24726a4d0f4e42420037ac64f9bda1db83f8e19d53f9b1d643d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
